# Generated by Django 4.2.4 on 2023-08-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
